#!/bin/bash
#SBATCH --job-name=example_name
#SBATCH --time=0-04:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=128G
#SBATCH --mail-user=example_email
#SBATCH --mail-type=END,FAIL
#SBATCH --output=../logs/%x-%j.out

module load python/3.10
source ~/project/venv/bin/activate

python ~/project/scripts/lightgbm.py \
    --csv ~/project/data/example_data.csv \
    --no_plots
